apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-b13m
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0040-tenant/tkrw-pr712-0075-0040-app/devfile-sample-b13m@sha256:0f7da84cc83355cf6e59f49aa6d8da71ad6df2f7a6d0d56cd9c8bc128ed90243
        name: my-nodejs
        resources: {}
status: {}
